spring:
  servlet:
    multipart:
      max-file-size: 1024MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/wp?useSSL=FALSE&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 88888888
    druid:
      # 数据源的其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的 filters，去掉后监控界面 sql 无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
server:
  port: 8888
mybatis:
  mapper-locations: com/dc/backend/mapper/impl/*.xml
  type-aliases-package: com/dc/backend/pojo
spark:
  app:
    name: Spring Boot Spark
  home: /user/local/spark
  master:
    uri: local
hadoop:
  home: /usr/local/Cellar/hadoop/3.2.1
  user: weilin
  hdfs:
    uri: localhost:8020
    userFilePath: /input
cluster:
  master: 127.0.0.1
  master2: 127.0.0.1
  slave1: 127.0.0.1
  slave2: 127.0.0.1
  slave3: 127.0.0.1
  login:
    name: weilin
    password: 981025
